modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "emeraldtools"
version = "${version}"
displayName = "Emerald Tools"
authors = "ModdedMC Studios"
description = '''
A Simple mod that adds tools made of emeralds
'''
#logoFile = ""

[[dependencies.emeraldtools]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emeraldtools]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.emeraldtools]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"